### ISSUE TITLE
Vendor_prop issue

### ISSUE THREAD

**Issue by Kirinline206** [ShivamKumarJha/android_tools#10]
./tools/system_vendor_prop.sh /home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml/system
./tools/system_vendor_prop.sh: line 45: 85
95: syntax error in expression (error token is "95")
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 1: unknown command: `,'
/home/user/dumpyara/android_tools/working/system.prop
/home/user/dumpyara/android_tools/working/vendor_prop.mk prepared!
vendor prop and system.prop is empty

**Comment by ShivamKumarJha** [comment]
Can you link me the ROM?

**Comment by ShivamKumarJha** [comment]
Also `./tools/system_vendor_prop.sh /home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml/` . You dont have to give `system` after rom path
