### ISSUE TITLE
vendor prop issue

### ISSUE THREAD

**Issue by Kirinline206** [ShivamKumarJha/android_tools#11]
./tools/system_vendor_prop.sh /home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml
find: '/home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml/vendor': No such file or directory
./tools/system_vendor_prop.sh: line 45: 85
95: syntax error in expression (error token is "95")
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 1: unknown command: `,'
/home/user/dumpyara/android_tools/working/system.prop
/home/user/dumpyara/android_tools/working/vendor_prop.mk prepared! or
./tools/system_vendor_prop.sh /home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml/
find: '/home/user/dumpyara/working/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml//vendor': No such file or directory
./tools/system_vendor_prop.sh: line 45: 85
95: syntax error in expression (error token is "95")
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 1: unknown command: `,'
/home/elias_souza/dumpyara/android_tools/working/system.prop

**Comment by Kirinline206** [comment]
https://mirrors.lolinet.com/firmware/moto/sanders/official/RETBR/XT1802_SANDERS_RETBR_8.1.0_OPS28.65-36-14_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip

**Comment by ShivamKumarJha** [comment]
Thanks for the link, will check it. seems like i need to add vendor/ check in that script

**Comment by Kirinline206** [comment]
> Thanks for the link, will check it. seems like i need to add vendor/ check in that script

oh thanks good lucky

**Comment by ShivamKumarJha** [comment]
Fixed
https://github.com/ShivamKumarJha/android_tools/commit/98ebcdbb8c268022468512ac271b3f05b017530c
