### ISSUE TITLE
New Hotword blobs on Android 11

### ISSUE THREAD

**Issue by GeoZac** [ShivamKumarJha/android_tools#19]
Hotword functionality requires the following files on Android 11
```
system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml
system_ext/framework/com.android.hotwordenrollment.common.util.jar
```
These file are currently listed under **Misc** section

Reference:
https://github.com/LineageOS/android_device_xiaomi_sdm845-common/commit/3ed901cdb10ba8cf8ee1cc62e76b1085ed93cbd4
https://github.com/LineageOS/android_device_oneplus_sm8250-common/commit/d3a5d47f75cb1d9041bb3cab7b891e20b77e7b50

**Comment by ShivamKumarJha** [comment]
Thanks, appreciate it
