### ISSUE TITLE
Nothing downloaded. Repo dir is empty. None file downloaded

### ISSUE THREAD

**Issue by AyaanSaleemMalik** [ShivamKumarJha/android_tools#2]
PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmjpeg.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmqjpeg_codec.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmqjpegdma.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libmpbase.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libois_lc898122.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/liboptizoom.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegdec.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegenc.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegenc_pipe.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libremosaic_daemon.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libseemore.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libtrueportrait.so
PATH: /home/Scissordragonboy/android/working/vendor/lib/libubifocus.so

Finished. Check /home/Scissordragonboy/android/working
Scissordragonboy@dump:~/android$ cd working
Scissordragonboy@dump:~/android/working$ ls
bin  etc  lib  lib64  list.txt  vendor
Scissordragonboy@dump:~/android/working$ cd vendor/lib
Scissordragonboy@dump:~/android/working/vendor/lib$ ls
Scissordragonboy@dump:~/android/working/vendor/lib$ cd ..
Scissordragonboy@dump:~/android/working/vendor$ cd lib
Scissordragonboy@dump:~/android/working/vendor/lib$ ls
Scissordragonboy@dump:~/android/working/vendor/lib$ cd ..
Scissordragonboy@dump:~/android/working/vendor$ cd ..
Scissordragonboy@dump:~/android/working$ cd lib
Scissordragonboy@dump:~/android/working/lib$ ls
  GNU nano 2.9.3                                                  list.txt                        
etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb
etc/acdbdata/QRD/QRD_General_cal.acdb:vendor/etc/acdbdata/QRD/QRD_General_cal.acdb
etc/acdbdata/QRD/QRD_Global_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb
etc/acdbdata/QRD/QRD_Handset_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb
etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb
etc/acdbdata/QRD/QRD_Headset_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb
etc/acdbdata/QRD/QRD_Speaker_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb
bin/mm-qcamera-daemon:vendor/bin/mm-qcamera-daemon
vendor/lib/libChamomilePA.so
vendor/lib/libchromaflash.so
vendor/lib/libflash_pmic.so
vendor/lib/libjpegdhw.so
vendor/lib/libjpegdmahw.so
vendor/lib/libjpegehw.so
vendor/lib/libmmcamera2_c2d_module.so
vendor/lib/libmmcamera2_cpp_module.so
vendor/lib/libmmcamera2_dcrf.so
vendor/lib/libmmcamera2_frame_algorithm.so
vendor/lib/libmmcamera2_iface_modules.so
vendor/lib/libmmcamera2_imglib_modules.so
vendor/lib/libmmcamera2_is.so
vendor/lib/libmmcamera2_isp_modules.so
vendor/lib/libmmcamera2_mct.so
vendor/lib/libmmcamera2_mct_shimlayer.so
vendor/lib/libmmcamera2_pp_buf_mgr.so
vendor/lib/libmmcamera2_pproc_modules.so
vendor/lib/libmmcamera2_q3a_core.so
vendor/lib/libmmcamera2_sensor_modules.so
vendor/lib/libmmcamera2_stats_algorithm.so
vendor/lib/libmmcamera2_stats_modules.so
vendor/lib/libmmcamera_atmel_at24c32e_eeprom.so
vendor/lib/libmmcamera_chromaflash_lib.so
vendor/lib/libmmcamera_csidtg.so
vendor/lib/libmmcamera_dbg.so
vendor/lib/libmmcamera_dcrf_lib.so
vendor/lib/libmmcamera_dummyalgo.so
vendor/lib/libmmcamera_dw9761b_2d_eeprom.so
vendor/lib/libmmcamera_eebinparse.so
vendor/lib/libmmcamera_eeprom_util.so
vendor/lib/libmmcamera_eztune_module.so
vendor/lib/libmmcamera_facedetection_lib.so
vendor/lib/libmmcamera_faceproc.so
vendor/lib/libmmcamera_faceproc2.so
vendor/lib/libmmcamera_hdr_gb_lib.so
vendor/lib/libmmcamera_imglib.so
vendor/lib/libmmcamera_imx258.so
vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so
vendor/lib/libmmcamera_imx258_gt24c32_eeprom.so
vendor/lib/libmmcamera_imx258_mono.so
vendor/lib/libmmcamera_imx258_mono_gt24c32_eeprom.so
vendor/lib/libmmcamera_imx258_ofilm.so
vendor/lib/libmmcamera_imx258_qtech.so
vendor/lib/libmmcamera_imx258_sunny.so
vendor/lib/libmmcamera_isp_abf40.so
vendor/lib/libmmcamera_isp_bcc40.so

Scissordragonboy@dump:~/android/working$ ls
bin  etc  lib  lib64  list.txt  vendor
Scissordragonboy@dump:~/android/working$ cd etc
Scissordragonboy@dump:~/android/working/etc$ ls
:vendor  acdbdata  camera
Scissordragonboy@dump:~/android/working/etc$ cd camera
Scissordragonboy@dump:~/android/working/etc/camera$ ls
:vendor
Scissordragonboy@dump:~/android/working/etc/camera$ cd :vemdor
-bash: cd: :vemdor: No such file or directory
Scissordragonboy@dump:~/android/working/etc/camera$ cd :vendor
Scissordragonboy@dump:~/android/working/etc/camera/:vendor$ ls
etc
Scissordragonboy@dump:~/android/working/etc/camera/:vendor$ cd etc
Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc$ ls
camera
Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc$ cd camera
Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc/camera$ ls
Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc/camera$ cd
Scissordragonboy@dump:~$ cd android

**Comment by ShivamKumarJha** [comment]
show me the command you used to call the script

**Comment by AyaanSaleemMalik** [comment]
./tools/dumpyara_blobs_downloader.sh < link to dump> path to proprietary-files.txt

**Comment by ShivamKumarJha** [comment]
show me the link

**Comment by AyaanSaleemMalik** [comment]
https://github.com/AndroidDumps/xiaomi_tissot_sprout_dump.git

**Comment by ShivamKumarJha** [comment]
wrong link, thats why. it has to raw link. try this

https://raw.githubusercontent.com/AndroidDumps/xiaomi_tissot_sprout_dump/tissot-user-9-PKQ1.180917.001-V10.0.13.0.PDHMIXM-release-keys/

**Comment by AyaanSaleemMalik** [comment]
Invalid request on this link

**Comment by AyaanSaleemMalik** [comment]
I will try with this  https://github.com/AndroidDumps/xiaomi_tissot_sprout_dump/tree/tissot-user-9-PKQ1.180917.001-V10.0.13.0.PDHMIXM-release-keys

**Comment by ShivamKumarJha** [comment]
> wrong link, thats why. it has to be raw link. try this
> 
> https://raw.githubusercontent.com/AndroidDumps/xiaomi_tissot_sprout_dump/tissot-user-9-PKQ1.180917.001-V10.0.13.0.PDHMIXM-release-keys/

this worked for me

**Comment by Vlastimil157** [comment]
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmjpeg.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmqjpeg_codec.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libmmqjpegdma.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libmpbase.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libois_lc898122.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/liboptizoom.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegdec.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegenc.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libqomx_jpegenc_pipe.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libremosaic_daemon.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libseemore.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libtrueportrait.so
> PATH: /home/Scissordragonboy/android/working/vendor/lib/libubifocus.so
> 
> Finished. Check /home/Scissordragonboy/android/working
> Scissordragonboy@dump:~/android$ cd working Scissordragonboy@dump:~/android/working$ ls
> bin etc lib lib64 list.txt vendor
> Scissordragonboy@dump:~/android/working$ cd vendor/lib Scissordragonboy@dump:~/android/working/vendor/lib$ ls
> Scissordragonboy@dump:~/android/working/vendor/lib$ cd .. Scissordragonboy@dump:~/android/working/vendor$ cd lib
> Scissordragonboy@dump:~/android/working/vendor/lib$ ls Scissordragonboy@dump:~/android/working/vendor/lib$ cd ..
> Scissordragonboy@dump:~/android/working/vendor$ cd .. Scissordragonboy@dump:~/android/working$ cd lib
> Scissordragonboy@dump:~/android/working/lib$ ls
> GNU nano 2.9.3 list.txt
> etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb
> etc/acdbdata/QRD/QRD_General_cal.acdb:vendor/etc/acdbdata/QRD/QRD_General_cal.acdb
> etc/acdbdata/QRD/QRD_Global_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb
> etc/acdbdata/QRD/QRD_Handset_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb
> etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb
> etc/acdbdata/QRD/QRD_Headset_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb
> etc/acdbdata/QRD/QRD_Speaker_cal.acdb:vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb
> bin/mm-qcamera-daemon:vendor/bin/mm-qcamera-daemon
> vendor/lib/libChamomilePA.so
> vendor/lib/libchromaflash.so
> vendor/lib/libflash_pmic.so
> vendor/lib/libjpegdhw.so
> vendor/lib/libjpegdmahw.so
> vendor/lib/libjpegehw.so
> vendor/lib/libmmcamera2_c2d_module.so
> vendor/lib/libmmcamera2_cpp_module.so
> vendor/lib/libmmcamera2_dcrf.so
> vendor/lib/libmmcamera2_frame_algorithm.so
> vendor/lib/libmmcamera2_iface_modules.so
> vendor/lib/libmmcamera2_imglib_modules.so
> vendor/lib/libmmcamera2_is.so
> vendor/lib/libmmcamera2_isp_modules.so
> vendor/lib/libmmcamera2_mct.so
> vendor/lib/libmmcamera2_mct_shimlayer.so
> vendor/lib/libmmcamera2_pp_buf_mgr.so
> vendor/lib/libmmcamera2_pproc_modules.so
> vendor/lib/libmmcamera2_q3a_core.so
> vendor/lib/libmmcamera2_sensor_modules.so
> vendor/lib/libmmcamera2_stats_algorithm.so
> vendor/lib/libmmcamera2_stats_modules.so
> vendor/lib/libmmcamera_atmel_at24c32e_eeprom.so
> vendor/lib/libmmcamera_chromaflash_lib.so
> vendor/lib/libmmcamera_csidtg.so
> vendor/lib/libmmcamera_dbg.so
> vendor/lib/libmmcamera_dcrf_lib.so
> vendor/lib/libmmcamera_dummyalgo.so
> vendor/lib/libmmcamera_dw9761b_2d_eeprom.so
> vendor/lib/libmmcamera_eebinparse.so
> vendor/lib/libmmcamera_eeprom_util.so
> vendor/lib/libmmcamera_eztune_module.so
> vendor/lib/libmmcamera_facedetection_lib.so
> vendor/lib/libmmcamera_faceproc.so
> vendor/lib/libmmcamera_faceproc2.so
> vendor/lib/libmmcamera_hdr_gb_lib.so
> vendor/lib/libmmcamera_imglib.so
> vendor/lib/libmmcamera_imx258.so
> vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so
> vendor/lib/libmmcamera_imx258_gt24c32_eeprom.so
> vendor/lib/libmmcamera_imx258_mono.so
> vendor/lib/libmmcamera_imx258_mono_gt24c32_eeprom.so
> vendor/lib/libmmcamera_imx258_ofilm.so
> vendor/lib/libmmcamera_imx258_qtech.so
> vendor/lib/libmmcamera_imx258_sunny.so
> vendor/lib/libmmcamera_isp_abf40.so
> vendor/lib/libmmcamera_isp_bcc40.so
> 
> Scissordragonboy@dump:~/android/working$ ls bin etc lib lib64 list.txt vendor Scissordragonboy@dump:~/android/working$ cd etc
> Scissordragonboy@dump:~/android/working/etc$ ls :vendor acdbdata camera Scissordragonboy@dump:~/android/working/etc$ cd camera
> Scissordragonboy@dump:~/android/working/etc/camera$ ls :vendor Scissordragonboy@dump:~/android/working/etc/camera$ cd :vemdor
> -bash: cd: :vemdor: No such file or directory
> Scissordragonboy@dump:~/android/working/etc/camera$ cd :vendor Scissordragonboy@dump:~/android/working/etc/camera/:vendor$ ls
> etc
> Scissordragonboy@dump:~/android/working/etc/camera/:vendor$ cd etc Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc$ ls
> camera
> Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc$ cd camera Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc/camera$ ls
> Scissordragonboy@dump:~/android/working/etc/camera/:vendor/etc/camera$ cd Scissordragonboy@dump:~$ cd android
