### ISSUE TITLE
About system requirements

### ISSUE THREAD

**Issue by Abgael** [ShivamKumarJha/android_tools#4]
Hello.
Just found out about this "Swiss Army Knife". I'm trying to run the proprietary-files.sh, system_vendor_prop.sh and vendor_prop.sh scripts, but with a lot of bugs. I not sure if this is a bug from the tool very own, a problem with my Ubuntu version, a problem with my Python version, my pip version or even with the Android dump version (Marshmallow).
This tool along with Android Blob Utility seems to be very promising for ROMs development, but it would be easier for new users give a proper feedback with a more detailed description of System Requirements.

**Comment by ShivamKumarJha** [comment]
proprietary-files.sh & vendor_prop.sh are not well supported for android version below oreo.
System requirements are minimal, especially for these two scripts.
