### ISSUE TITLE
Some scripts are not working

### ISSUE THREAD

**Issue by SeimoDev** [ShivamKumarJha/android_tools#49]
I have run "tools/rom_extract.sh" ,but in the dumps folder ,the "Recovery" and "tz" folders are blank.What's more,when I ran tools/dummy_dt.sh , it show me `find: '/home/seimo/android_tools/ishtar.zip/': Not a directory` ,but I'm sure I give it a file.

However,I have no more logs could be gave.I think maybe it's because of Android 13 or erosfs file system?I'm new for this thing,please help me.

Device: Xiaomi 13 Ultra (ishtar)
Android version of the unpacked ROM: Android 13
Working system: Ubuntu 22.04.3 LTS
The ROM: [Download](https://k3cn1p7iq4in2hrdei5f9s895ltf0umuja9kmobtms9mps9i3ojvu1pi.qc.dolfincdnx.net:10443/xdispatch27a345746f06a758/hugeota.d.miui.com/V14.0.17.0.TMACNXM/miui_ISHTAR_V14.0.17.0.TMACNXM_16baf7ce2c_13.0.zip?bsreqid=9c6f006bebdbc4e002b925d99ac3867e&bsxdisp=se)

**Comment by ShivamKumarJha** [comment]
Hi, I haven't maintained this for a long time now. Could you check if [this](https://github.com/AndroidDumps/dumpyara) works?

**Comment by SeimoDev** [comment]
OK,I will try.
