### ISSUE TITLE
Not working on arm device

### ISSUE THREAD

**Issue by TTTT55** [ShivamKumarJha/android_tools#5]
Is the script mainly made for arm64 devices? 
The proprietary-files.txt as well as vendor tree generated with this script on an arm device skips a lot of files. Please make it compitable for arm also..

**Comment by ShivamKumarJha** [comment]
proprietary-files.sh doesn't support android version below 8

**Comment by TTTT55** [comment]
My device is launched with android 9

**Comment by ShivamKumarJha** [comment]
link me the ROM zip. Will see

**Comment by TTTT55** [comment]
Which rom? Any source built booting rom (which have closed source by a dev) or rom that I booted with prebuilt vendor image ?

**Comment by ShivamKumarJha** [comment]
stock rom of your device ...

**Comment by TTTT55** [comment]
ROM link:-
http://bigota.d.miui.com/V10.2.5.0.PCMMIXM/pine_global_images_V10.2.5.0.PCMMIXM_20190805.0000.00_9.0_global_efb78ff9c3.tgz

The dump is available here:-
https://github.com/AndroidDumps/xiaomi_pine_dump/tree/pine-user-9-PKQ1.190319.001-V10.2.5.0.PCMMIXM-release-keys

**Comment by ShivamKumarJha** [comment]
https://github.com/AndroidBlobs/device_xiaomi_pine/tree/pine-user-9-PKQ1.190319.001-V11.0.1.0.PCMEUOR-release-keys?files=1

seems fine

**Comment by TTTT55** [comment]
Oh.  Are you telling me to use this miui version ? 
(I'm using miui 10 as base rom because Miui 11 not boots with kernel Source released by Xiaomi.)

**Comment by ShivamKumarJha** [comment]
No i didn't mean that. In case you want miui 10 list: 
https://github.com/AndroidBlobs/device_xiaomi_pine
I'm closing this issue as script is handling this device well enough.
