### ISSUE TITLE
system.prop and vendor_prop.mk are empty

### ISSUE THREAD

**Issue by KenHV** [ShivamKumarJha/android_tools#7]
i used the system_vendor_prop.sh script to generate props from vince_global dump on androiddumps repo, and the generated files were empty. this is the output i got when i ran the command.

```
KenHV@kenhv:~/android_tools$ ./tools/system_vendor_prop.sh ~/dump
find: '/home/KenHV/dump/vendor': No such file or directory
./tools/system_vendor_prop.sh: line 45: 41
51: syntax error in expression (error token is "51")
sed: -e expression #1, char 3: unknown command: `
'
sed: -e expression #1, char 1: unknown command: `,'
/home/KenHV/android_tools/working/system.prop
/home/KenHV/android_tools/working/vendor_prop.mk prepared!
```

**Comment by ShivamKumarJha** [comment]
Give the vince dump folder as argument

**Comment by KenHV** [comment]
i did, i was able to generate both vendor and dummy tree from the dump and the props are still empty there. i checked the androidblobs repos and its empty in there as well.

**Comment by ShivamKumarJha** [comment]
> i used the system_vendor_prop.sh script to generate props from vince_global dump on androiddumps repo, and the generated files were empty. this is the output i got when i ran the command.
> 
> ```
> KenHV@kenhv:~/android_tools$ ./tools/system_vendor_prop.sh ~/dump
> find: '/home/KenHV/dump/vendor': No such file or directory
> ./tools/system_vendor_prop.sh: line 45: 41
> 51: syntax error in expression (error token is "51")
> sed: -e expression #1, char 3: unknown command: `
> '
> sed: -e expression #1, char 1: unknown command: `,'
> /home/KenHV/android_tools/working/system.prop
> /home/KenHV/android_tools/working/vendor_prop.mk prepared!
> ```

./tools/system_vendor_prop.sh ~/dump

Above command is what you've used. It isn't the vince dump directory.

**Comment by ShivamKumarJha** [comment]
Will inspect it

**Comment by KenHV** [comment]
Thank you!
