### ISSUE TITLE
it doesnt work on nougat? 

### ISSUE THREAD

**Issue by psychicgirl2020** [ShivamKumarJha/android_tools#9]
cause i tried to generate an dummy tree it shows pre oreo roms not supported

**Comment by ShivamKumarJha** [comment]
Well like the script said, nougat & previous android versions are not supported. You can comment this https://github.com/ShivamKumarJha/android_tools/blob/master/tools/dummy_dt.sh#L62 else block to get the dummy dt, however it might not be that good. I dont plan on adding pre oreo support right now
